### ISSUE TITLE
CACAO coordination checklist

### ISSUE THREAD

**Issue by oed** [ceramicnetwork/cacao#4]
Creating this checklist to keep track of things needed to establish Cacao as a legit standard for object capabilities. Things may be added here over time as needed.

- [ ] CAIP related work
  - [ ] Get CACAO draft merged: https://github.com/ChainAgnostic/CAIPs/pull/74
  - [ ] Create a registry for supported signature types (e.g. `eip4361-eip191`)
  - [ ] Create a guide / caip for how to use CACAO together with JWS (i.e. `cap` header)
- [ ] Standards work
  - [ ] Register `cap` protected header with [IANA](https://www.iana.org/assignments/jose/jose.xhtml)
  - [ ] https://github.com/spruceid/ssi/issues/362
  
FYI, @ukstv @haardikk21 @wyc @bumblefudge
